DayliNotesWebMVC/Models/ErrorViewModel.cs
namespace DayliNotesWebMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DayliNotesWebMVC/Controllers/AuthorisationController.cs
using DailyNotesWebApi;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;
using DayliNotes.Core;
using DayliNotesWebMVC.Classes;

namespace DayliNotesWebMVC.Controllers
{
    public class AuthorisationController : Controller
    {
        private readonly ILogger<AuthorisationController> _logger;
        private readonly HttpClient _client;
        public Uri baseAddres = new Uri("https://localhost:7210/api");
        public AuthorisationController(ILogger<AuthorisationController> logger)
        {
            _logger = logger;
            _client = new HttpClient();
            _client.BaseAddress = baseAddres;
        }

        public IActionResult About()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(string? login, string? password)
        {
            if (string.IsNullOrEmpty(login) || string.IsNullOrEmpty(password))
                return View();
            Client client = new Client();
            HttpResponseMessage response = _client.GetAsync(baseAddres + "/DailyNotes/GetClientByLogin/"+login).Result;
            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;  
                client = JsonConvert.DeserializeObject<Client>(data);
                if (client.Password == password)
                    return RedirectToAction("Notes", "Note", new { clientId = client.ClientId});
            }
            ViewBag.Error = "Неправильный логин или пароль";
            ViewBag.Login = login;
            return View();
        }

        [HttpGet]
        public IActionResult Registration()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Registration(ClientViewModel client)
        {
            if(client == null)
                return View();
            //string data = JsonConvert.SerializeObject(client);
            //StringContent content = new StringContent(data.ToLower(), Encoding.UTF8, "application/json");
            //HttpResponseMessage response = _client.PostAsync(baseAddres + "/DailyNotes/CreateClient", content).Result;
            HttpResponseMessage response = _client.PostAsJsonAsync(baseAddres + "/DailyNotes/CreateClient", client).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Login");
            }
            return View();
        }
    }
}

DayliNotesWebMVC/Controllers/NoteController.cs
using DailyNotesWebApi;
using DayliNotes.Core;
using DayliNotesWebMVC.Classes;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using NuGet.Protocol;
using System.Text;
using System.Text.Json.Nodes;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace DayliNotesWebMVC.Controllers
{
    public class NoteController : Controller
    {
        private readonly ILogger<NoteController> _logger;
        private readonly HttpClient _client;
        public Uri baseAddres = new Uri("https://localhost:7210/api");
        public static int _clientId;
        public NoteController(ILogger<NoteController> logger)
        {
            _logger = logger;
            _client = new HttpClient();
            _client.BaseAddress = baseAddres;
        }

        public async Task<IActionResult> Notes(int clientId)
        {
            HttpResponseMessage response = await _client.GetAsync(baseAddres + "/DailyNotes/GetNotesByClientId/" + clientId);
            if(response.IsSuccessStatusCode)
            {
                string data = await response.Content.ReadAsStringAsync();
                JArray result = JArray.Parse(data);
                var notes = result.ToObject<List<NoteViewModel>>();

                //var listNotes = result["items"].Value<JArray>();
                //List<NoteViewModel> notes = listNotes.ToObject<List<NoteViewModel>>();


                //var listNotes = JsonConvert.DeserializeObject(data);
                //var notes = ((JArray)listNotes).Select(x => new NoteViewModel
                //{
                //    NoteId = (int)x["noteId"],
                //    ClientId = (int)x["ClientId"],
                //    NoteTypeId = (int)x["noteTypeId"],
                //    NoteText = (string)x["noteText"],
                //    EditDate = (DateTime)x["editDate"],
                //    NoteTitle = (string)x["noteTitle"]
                //}).ToList();
                
                ViewBag.ClientId = clientId;
                return View(notes);
            }
            return View(null);
        }

        [HttpGet]
        public IActionResult CreateNote(int clientId)
        {
            return View(clientId);
        }

        [HttpPost]
        public async Task<IActionResult> CreateNote(string? NoteText, string? NoteTitle, int ClientId)
        {
            if (NoteText == null)
                return View(ClientId);
            HttpResponseMessage response = await _client.PostAsJsonAsync(baseAddres + "/DailyNotes/CreateNote", new NoteViewModel()
            {
                ClientId = ClientId,
                NoteTypeId = 1,
                NoteText = NoteText,
                EditDate = DateTime.Now,
                NoteTitle = NoteTitle
            });
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Notes", new { clientId = ClientId });
            }
            return View(ClientId);
        }

        [HttpGet]
        public async Task<IActionResult> UpdateNote(int noteId)
        {
            var response = await _client.GetAsync(baseAddres + "/DailyNotes/GetNoteById/" + noteId);
            if (response.IsSuccessStatusCode)
            {
                string data = await response.Content.ReadAsStringAsync();
                Note note = JsonConvert.DeserializeObject<Note>(data);
                return View(note);
            }
            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> UpdateNote(Note note)
        {
            var noteViewModel = new NoteViewModel()
            {
                NoteId = note.NoteId,
                ClientId = note.ClientId,
                NoteTypeId = 1,
                NoteText = note.NoteText,
                EditDate = DateTime.Now,
                NoteTitle = note.NoteTitle
            };

            var response = await _client.PutAsJsonAsync(baseAddres + "/DailyNotes/UpdateNote", noteViewModel);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Notes", new { clientId = note.ClientId });
            }
            return View(note);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteNote(int noteId, int _clientId)
        {
            var response = await _client.DeleteAsync(baseAddres + "/DailyNotes/DeleteNote/" + noteId);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Notes", new { clientId = _clientId });
            }
            return NotFound();
        }
    }
}

DayliNotesWebMVC/Views/Authorisation/About.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<link rel="stylesheet" href="~/css/AboutStyles.css" />
<style>
    .cendiv{
        text-align:center;
        position: absolute;
        top: 30%;
        left: 25%;
        right: 50%;
        height: 30%;
        width: 50%;
    }
    .text{
        font-size: 48px;
        color: aliceblue;
    }

    body {
        width: 100%;
        min-width: 960px;
        overflow: hidden;
    }

</style>
<body>
    <div class="cendiv">
        <p>
            <h1 class="text">Добро пожаловать на сайт для ежедневных заметок</h1>
        </p>
        <p>
           <div class="wrapper">
              <div class="link_wrapper">
                <a href="Authorisation/Login">Попробовать!</a>
                <div class="icon">
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 268.832 268.832">
                    <path d="M265.17 125.577l-80-80c-4.88-4.88-12.796-4.88-17.677 0-4.882 4.882-4.882 12.796 0 17.678l58.66 58.66H12.5c-6.903 0-12.5 5.598-12.5 12.5 0 6.903 5.597 12.5 12.5 12.5h213.654l-58.66 58.662c-4.88 4.882-4.88 12.796 0 17.678 2.44 2.44 5.64 3.66 8.84 3.66s6.398-1.22 8.84-3.66l79.997-80c4.883-4.882 4.883-12.796 0-17.678z"/>
                  </svg>
                </div>
              </div>

            </div>
        </p>
    </div>
</body>

DayliNotesWebMVC/Views/Authorisation/Login.cshtml
@{
}
@model ClientViewModel
<link rel="stylesheet" href="~/css/AuthorisationStyles.css" />
<body>
    <div class="login-container">
        <h1 class="authorization-label">Авторизация</h1>
        <form asp-action="Login" asp-controller="Authorisation" method="post" class="login-form">
            <div class="centered-div">
                <p>
                    <input type="text"  name="login" class="login-field" placeholder="Login" value="@ViewBag.Login"/>
                </p>
                <p>
                    <input type="password" name="password" class="password-field" placeholder="Password" />
                </p>
                <p style="color: purple">@ViewBag.Error</p>
                <p>
                        <input type="submit" value="Войти" class="register-button" />
                </p>
                <a href="./Registration" style="color: purple;">Создать аккаунт</a>
            </div>
        </form>
    </div>
</body>

DayliNotesWebMVC/Views/Authorisation/Registration.cshtml
@{
}
@model Client
<link rel="stylesheet" href="~/css/AuthorisationStyles.css" />

<body>
    <div class="login-container">

        <h1 class="authorization-label">Регистрация</h1>
        <form asp-action="Registration" asp-controller="Authorisation" method="post" class="login-form">
            <p>
                <input asp-for="Login" placeholder="Login" class="login-field"/>
                <span asp-validation-for="Login"></span>
            </p>
            <p>
                 <input asp-for="Email" placeholder="Email" class="login-field"/>
                 <span asp-validation-for="Email"></span>
            </p>
            <p>
                <input asp-for="Password" placeholder="Password" type="password" class="password-field"/>
                <span asp-validation-for="Password"></span>
            </p>
            <p>
                <input type="submit" value="Войти" class="register-button" />
            </p>
        </form>
    </div>
</body>

DayliNotesWebMVC/Views/Note/CreateNote.cshtml
@{
}

<style>

    .note {
  background-color: #fff;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
  padding: 20px;
}

.note-title {
  display: block;
  width: 100%;
  font-size: 24px;
  margin-bottom: 10px;
  border: none;
  border-bottom: 2px solid #ccc;
  padding: 5px;
}

.note-content {
  display: block;
  width: 100%;
  height: 600px;
  font-size: 16px;
  border: none;
  border-bottom: 2px solid #ccc;
  padding: 5px;
}

.note-save {
  display: block;
  margin-top: 10px;
  padding: 10px;
  background-color: #ccc;
  border: none;
  cursor: pointer;
  
}
</style>
@model int
<body>
    <div class="note">
        <form asp-action="CreateNote" asp-controller="Note" method="post">
            <input type="text" name="NoteTitle" class="note-title" placeholder="Title">
            <textarea class="note-content" name="NoteText" placeholder="Enter your note here"></textarea>
            <input type="number" name="ClientId" hidden value="@Model" />
            <input type="submit" class="note-save" value="Сохранить" />
        </form>
        <form asp-action="Notes" asp-controller="Note" asp-route-ClientId="@Model" method="get">
            <input type="number" name="ClientId" hidden value="@Model" />
            <input type="submit" class="note-save" value="Назад" />
        </form>
    </div>
</body>

DayliNotesWebMVC/Views/Note/Notes.cshtml
@{
}
@model List<NoteViewModel>
<link rel="stylesheet" href="styles.css">
<style>
    .container {
        font-size: 0;
        border: 3px, solid, green;
    }

    .box {
      display: inline-block;
      width: 210px;
      height: 280px;
      margin-right: 20px;
      margin-bottom: 20px;
      border: 2px solid green;
      overflow: hidden;
      border-radius: 10px;
      background-image: linear-gradient(to top, rgba(green, 0.5), transparent);
    }

    .box p {
        font-size: 16px;          
        text-align: center;   
    }
    .noteText {
        color: forestgreen;
        height: 55px;
    }
    
    .noteTitle {
        color: lightgoldenrodyellow;
        height: 30px;
    }

    .plus {
        display: block;
        width: 200px;
        height: 200px;
        background-color: black;
        color: lightyellow;
        font-size: 32px;
        border: none;
        cursor: pointer;
    }

    .exit-container {
        position: absolute;
        top: 0;
        right: 0;
        margin: 20px;
    }

    .exit-button {
        width: 150px;
        font-size: 16px;
        padding: 10px;
        background-color: #ccc;
        border: none;
        cursor: pointer;
    }

    .btn-new {
    border-radius: 10px;
    color: white;
    transition: .2s linear;
    background: forestgreen;
    }

    .btn-new:hover {
        box-shadow: 0 0 0 2px green, 0 0 0 4px black;
    }
</style>

<body>
    <div class="exit-container">
        <form asp-action="Login" asp-controller="Authorisation" method="get">
            <input type="submit" value="Выйти из аккаунта" class="exit-button" />
        </form>
    </div>

    <div class="container" >
        @Html.BlockGenerate(Model)
        <div class="box">
            <p>
                <a class="plus" style="height: 250px; padding-top: 65px" href="/Note/CreateNote?clientId=@ViewBag.ClientId">Добавить заметку</a>
            </p>
        </div>
    </div>
    
</body>

DayliNotesWebMVC/Views/Note/UpdateNote.cshtml
@{
}
@model Note

<style>

    .note {
        background-color: #fff;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
        padding: 20px;
    }

    .note-title {
        display: block;
        width: 100%;
        font-size: 24px;
        margin-bottom: 10px;
        border: none;
        border-bottom: 2px solid #ccc;
        padding: 5px;
    }

    .note-content {
        display: block;
        width: 100%;
        height: 600px;
        font-size: 16px;
        border: none;
        border-bottom: 2px solid #ccc;
        padding: 5px;
    }

    .note-save {
        display: block;
        margin-top: 10px;
        padding: 10px;
        background-color: #ccc;
        border: none;
        cursor: pointer;
    }
</style>

<body>
    <div class="note">
        <form asp-action="UpdateNote" asp-controller="Note" method="post">
            <input type="number" hidden value="@Model.ClientId" name="ClientId" />
            <input type="number" hidden value="@Model.NoteId" name="NoteId" />
            <input asp-for="NoteTitle" class="note-title" placeholder="Title">
            <textarea class="note-content" asp-for="NoteText" placeholder="Enter your note here"></textarea>
            <input type="submit" class="note-save" value="Сохранить" />
        </form>
        <form asp-action="Notes" asp-controller="Note" asp-route-clientId="@Model.ClientId" method="get">
            <input type="number" name="clientId" hidden value="@Model.ClientId" />
            <input type="submit" class="note-save" value="Назад" />
        </form>
    </div>
</body>

DayliNotesWebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DayliNotesWebMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DayliNotesWebMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Layout.css" />
</head>

<body style="background-color: black">
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer >
        <div class="footer">
            <a href="https://vk.com/makklaud89" style="font-family: 'Montserrat', sans-serif; margin: 15px; font-size: 24px;  text-decoration: none;">by makk1aud</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>